#!/usr/bin/env bash
# Generate AGENT_THIRD_PARTY_LICENSES at the repo root by walking every Go
# module referenced in agent-client/go.sum and aggregating its LICENSE text.
#
# Output covers all release binaries (linux/darwin/windows x amd64/arm64) at
# once: we union the dependency trees rather than running per-platform, since
# any module hashed in go.sum is something we may ship into one of those
# binaries (some deps are platform-specific — wincred is Windows-only, dbus
# is Linux-only — and would otherwise be missed by a single-platform pass).

set -euo pipefail

cd "$(dirname "$0")/.."

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required" >&2
  exit 1
fi

go mod download

OUT="../AGENT_THIRD_PARTY_LICENSES"

{
  printf '# shellwatch-agent — Third-Party License Notices\n\n'
  printf 'Aggregated license texts of every Go module referenced in `agent-client/go.sum`. Some modules are platform-specific (e.g. `wincred` is Windows-only, `dbus/v5` is Linux-only) but are listed here regardless so this single bundle covers every released binary.\n\n'
  printf 'Generated by `agent-client/scripts/bundle-licenses.sh`.\n\n'
  printf 'Generated at: %s\n\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf -- '---\n\n'

  go list -m -json all \
    | jq -r 'select(.Main != true and .Dir != null) | "\(.Path)\t\(.Version)\t\(.Dir)"' \
    | sort \
    | while IFS=$'\t' read -r path version dir; do
        printf '## %s@%s\n\n' "$path" "$version"
        lic=$(find "$dir" -maxdepth 1 -type f \( \
          -iname 'LICENSE*' -o -iname 'COPYING*' -o \
          -iname 'LICENCE*' -o -iname 'NOTICE*' \
        \) -print -quit || true)
        if [ -z "$lic" ]; then
          printf '_(No LICENSE file shipped with this module — license declared in module metadata only)_\n\n'
        else
          printf '```\n'
          cat "$lic"
          printf '\n```\n\n'
        fi
        printf -- '---\n\n'
      done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines, $(du -h "$OUT" | cut -f1))"
