// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"encoding/json"
	"fmt"
)

const (
	BearerUiScopes bearerUiContextKey = "bearerUi.Scopes"
)

// Defines values for EndpointUserVerification.
const (
	EndpointUserVerificationDiscouraged EndpointUserVerification = "discouraged"
	EndpointUserVerificationPreferred   EndpointUserVerification = "preferred"
	EndpointUserVerificationRequired    EndpointUserVerification = "required"
)

// Valid indicates whether the value is a known member of the EndpointUserVerification enum.
func (e EndpointUserVerification) Valid() bool {
	switch e {
	case EndpointUserVerificationDiscouraged:
		return true
	case EndpointUserVerificationPreferred:
		return true
	case EndpointUserVerificationRequired:
		return true
	default:
		return false
	}
}

// Defines values for PendingActionViewStatus.
const (
	PendingActionViewStatusCompleted PendingActionViewStatus = "completed"
	PendingActionViewStatusDenied    PendingActionViewStatus = "denied"
	PendingActionViewStatusExpired   PendingActionViewStatus = "expired"
	PendingActionViewStatusPending   PendingActionViewStatus = "pending"
)

// Valid indicates whether the value is a known member of the PendingActionViewStatus enum.
func (e PendingActionViewStatus) Valid() bool {
	switch e {
	case PendingActionViewStatusCompleted:
		return true
	case PendingActionViewStatusDenied:
		return true
	case PendingActionViewStatusExpired:
		return true
	case PendingActionViewStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for PendingActionViewType.
const (
	KeyApprove   PendingActionViewType = "key-approve"
	WebauthnSign PendingActionViewType = "webauthn-sign"
)

// Valid indicates whether the value is a known member of the PendingActionViewType enum.
func (e PendingActionViewType) Valid() bool {
	switch e {
	case KeyApprove:
		return true
	case WebauthnSign:
		return true
	default:
		return false
	}
}

// Defines values for PendingActionViewUserVerification.
const (
	PendingActionViewUserVerificationDiscouraged PendingActionViewUserVerification = "discouraged"
	PendingActionViewUserVerificationPreferred   PendingActionViewUserVerification = "preferred"
	PendingActionViewUserVerificationRequired    PendingActionViewUserVerification = "required"
)

// Valid indicates whether the value is a known member of the PendingActionViewUserVerification enum.
func (e PendingActionViewUserVerification) Valid() bool {
	switch e {
	case PendingActionViewUserVerificationDiscouraged:
		return true
	case PendingActionViewUserVerificationPreferred:
		return true
	case PendingActionViewUserVerificationRequired:
		return true
	default:
		return false
	}
}

// Defines values for SessionLifecycleRowSource.
const (
	SessionLifecycleRowSourceMcp SessionLifecycleRowSource = "mcp"
	SessionLifecycleRowSourceSsh SessionLifecycleRowSource = "ssh"
	SessionLifecycleRowSourceUi  SessionLifecycleRowSource = "ui"
)

// Valid indicates whether the value is a known member of the SessionLifecycleRowSource enum.
func (e SessionLifecycleRowSource) Valid() bool {
	switch e {
	case SessionLifecycleRowSourceMcp:
		return true
	case SessionLifecycleRowSourceSsh:
		return true
	case SessionLifecycleRowSourceUi:
		return true
	default:
		return false
	}
}

// Defines values for SessionLifecycleRowStatus.
const (
	SessionLifecycleRowStatusClosed SessionLifecycleRowStatus = "closed"
	SessionLifecycleRowStatusError  SessionLifecycleRowStatus = "error"
	SessionLifecycleRowStatusOpen   SessionLifecycleRowStatus = "open"
)

// Valid indicates whether the value is a known member of the SessionLifecycleRowStatus enum.
func (e SessionLifecycleRowStatus) Valid() bool {
	switch e {
	case SessionLifecycleRowStatusClosed:
		return true
	case SessionLifecycleRowStatusError:
		return true
	case SessionLifecycleRowStatusOpen:
		return true
	default:
		return false
	}
}

// Defines values for SigningRequestRowOutcome.
const (
	SigningRequestRowOutcomeApproved    SigningRequestRowOutcome = "approved"
	SigningRequestRowOutcomeCancelled   SigningRequestRowOutcome = "cancelled"
	SigningRequestRowOutcomeDenied      SigningRequestRowOutcome = "denied"
	SigningRequestRowOutcomeExpired     SigningRequestRowOutcome = "expired"
	SigningRequestRowOutcomeLessThannil SigningRequestRowOutcome = "<nil>"
)

// Valid indicates whether the value is a known member of the SigningRequestRowOutcome enum.
func (e SigningRequestRowOutcome) Valid() bool {
	switch e {
	case SigningRequestRowOutcomeApproved:
		return true
	case SigningRequestRowOutcomeCancelled:
		return true
	case SigningRequestRowOutcomeDenied:
		return true
	case SigningRequestRowOutcomeExpired:
		return true
	case SigningRequestRowOutcomeLessThannil:
		return true
	default:
		return false
	}
}

// Defines values for SigningRequestRowSource.
const (
	SigningRequestRowSourceAgentForwarding SigningRequestRowSource = "agent-forwarding"
	SigningRequestRowSourceAgentProxy      SigningRequestRowSource = "agent-proxy"
	SigningRequestRowSourceEndpointAuth    SigningRequestRowSource = "endpoint-auth"
)

// Valid indicates whether the value is a known member of the SigningRequestRowSource enum.
func (e SigningRequestRowSource) Valid() bool {
	switch e {
	case SigningRequestRowSourceAgentForwarding:
		return true
	case SigningRequestRowSourceAgentProxy:
		return true
	case SigningRequestRowSourceEndpointAuth:
		return true
	default:
		return false
	}
}

// Defines values for StatusCreatedStatus.
const (
	Created StatusCreatedStatus = "created"
)

// Valid indicates whether the value is a known member of the StatusCreatedStatus enum.
func (e StatusCreatedStatus) Valid() bool {
	switch e {
	case Created:
		return true
	default:
		return false
	}
}

// Defines values for StatusDeletedStatus.
const (
	Deleted StatusDeletedStatus = "deleted"
)

// Valid indicates whether the value is a known member of the StatusDeletedStatus enum.
func (e StatusDeletedStatus) Valid() bool {
	switch e {
	case Deleted:
		return true
	default:
		return false
	}
}

// Defines values for StatusUpdatedStatus.
const (
	Updated StatusUpdatedStatus = "updated"
)

// Valid indicates whether the value is a known member of the StatusUpdatedStatus enum.
func (e StatusUpdatedStatus) Valid() bool {
	switch e {
	case Updated:
		return true
	default:
		return false
	}
}

// Defines values for StepUpErrorCode.
const (
	StepupExpired      StepUpErrorCode = "stepup_expired"
	StepupRequired     StepUpErrorCode = "stepup_required"
	StepupWrongAccount StepUpErrorCode = "stepup_wrong_account"
	StepupWrongAction  StepUpErrorCode = "stepup_wrong_action"
)

// Valid indicates whether the value is a known member of the StepUpErrorCode enum.
func (e StepUpErrorCode) Valid() bool {
	switch e {
	case StepupExpired:
		return true
	case StepupRequired:
		return true
	case StepupWrongAccount:
		return true
	case StepupWrongAction:
		return true
	default:
		return false
	}
}

// Defines values for TerminalSource.
const (
	TerminalSourceMcp TerminalSource = "mcp"
	TerminalSourceSsh TerminalSource = "ssh"
	TerminalSourceUi  TerminalSource = "ui"
)

// Valid indicates whether the value is a known member of the TerminalSource enum.
func (e TerminalSource) Valid() bool {
	switch e {
	case TerminalSourceMcp:
		return true
	case TerminalSourceSsh:
		return true
	case TerminalSourceUi:
		return true
	default:
		return false
	}
}

// Defines values for TerminalStatus.
const (
	TerminalStatusClosed  TerminalStatus = "closed"
	TerminalStatusClosing TerminalStatus = "closing"
	TerminalStatusError   TerminalStatus = "error"
	TerminalStatusOpen    TerminalStatus = "open"
	TerminalStatusOpening TerminalStatus = "opening"
)

// Valid indicates whether the value is a known member of the TerminalStatus enum.
func (e TerminalStatus) Valid() bool {
	switch e {
	case TerminalStatusClosed:
		return true
	case TerminalStatusClosing:
		return true
	case TerminalStatusError:
		return true
	case TerminalStatusOpen:
		return true
	case TerminalStatusOpening:
		return true
	default:
		return false
	}
}

// Defines values for DenyAction200JSONResponseBodyStatus.
const (
	DenyAction200JSONResponseBodyStatusDenied DenyAction200JSONResponseBodyStatus = "denied"
)

// Valid indicates whether the value is a known member of the DenyAction200JSONResponseBodyStatus enum.
func (e DenyAction200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case DenyAction200JSONResponseBodyStatusDenied:
		return true
	default:
		return false
	}
}

// Defines values for ListAuditSigningsParamsSource.
const (
	ListAuditSigningsParamsSourceAgentForwarding ListAuditSigningsParamsSource = "agent-forwarding"
	ListAuditSigningsParamsSourceAgentProxy      ListAuditSigningsParamsSource = "agent-proxy"
	ListAuditSigningsParamsSourceEndpointAuth    ListAuditSigningsParamsSource = "endpoint-auth"
)

// Valid indicates whether the value is a known member of the ListAuditSigningsParamsSource enum.
func (e ListAuditSigningsParamsSource) Valid() bool {
	switch e {
	case ListAuditSigningsParamsSourceAgentForwarding:
		return true
	case ListAuditSigningsParamsSourceAgentProxy:
		return true
	case ListAuditSigningsParamsSourceEndpointAuth:
		return true
	default:
		return false
	}
}

// Defines values for ListAuditSigningsParamsOutcome.
const (
	ListAuditSigningsParamsOutcomeApproved  ListAuditSigningsParamsOutcome = "approved"
	ListAuditSigningsParamsOutcomeCancelled ListAuditSigningsParamsOutcome = "cancelled"
	ListAuditSigningsParamsOutcomeDenied    ListAuditSigningsParamsOutcome = "denied"
	ListAuditSigningsParamsOutcomeExpired   ListAuditSigningsParamsOutcome = "expired"
)

// Valid indicates whether the value is a known member of the ListAuditSigningsParamsOutcome enum.
func (e ListAuditSigningsParamsOutcome) Valid() bool {
	switch e {
	case ListAuditSigningsParamsOutcomeApproved:
		return true
	case ListAuditSigningsParamsOutcomeCancelled:
		return true
	case ListAuditSigningsParamsOutcomeDenied:
		return true
	case ListAuditSigningsParamsOutcomeExpired:
		return true
	default:
		return false
	}
}

// Defines values for FinishAccountRegistration200JSONResponseBodyVerified.
const (
	FinishAccountRegistration200JSONResponseBodyVerifiedTrue FinishAccountRegistration200JSONResponseBodyVerified = true
)

// Valid indicates whether the value is a known member of the FinishAccountRegistration200JSONResponseBodyVerified enum.
func (e FinishAccountRegistration200JSONResponseBodyVerified) Valid() bool {
	switch e {
	case FinishAccountRegistration200JSONResponseBodyVerifiedTrue:
		return true
	default:
		return false
	}
}

// Defines values for RevokeAllAuthorizedClients200JSONResponseBodyStatus.
const (
	RevokedAll RevokeAllAuthorizedClients200JSONResponseBodyStatus = "revoked_all"
)

// Valid indicates whether the value is a known member of the RevokeAllAuthorizedClients200JSONResponseBodyStatus enum.
func (e RevokeAllAuthorizedClients200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case RevokedAll:
		return true
	default:
		return false
	}
}

// Defines values for RevokeAuthorizedClient200JSONResponseBodyStatus.
const (
	RevokeAuthorizedClient200JSONResponseBodyStatusRevoked RevokeAuthorizedClient200JSONResponseBodyStatus = "revoked"
)

// Valid indicates whether the value is a known member of the RevokeAuthorizedClient200JSONResponseBodyStatus enum.
func (e RevokeAuthorizedClient200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case RevokeAuthorizedClient200JSONResponseBodyStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for CreateEndpointJSONBodyUserVerification.
const (
	CreateEndpointJSONBodyUserVerificationDiscouraged CreateEndpointJSONBodyUserVerification = "discouraged"
	CreateEndpointJSONBodyUserVerificationPreferred   CreateEndpointJSONBodyUserVerification = "preferred"
	CreateEndpointJSONBodyUserVerificationRequired    CreateEndpointJSONBodyUserVerification = "required"
)

// Valid indicates whether the value is a known member of the CreateEndpointJSONBodyUserVerification enum.
func (e CreateEndpointJSONBodyUserVerification) Valid() bool {
	switch e {
	case CreateEndpointJSONBodyUserVerificationDiscouraged:
		return true
	case CreateEndpointJSONBodyUserVerificationPreferred:
		return true
	case CreateEndpointJSONBodyUserVerificationRequired:
		return true
	default:
		return false
	}
}

// Defines values for UpdateEndpointJSONBodyUserVerification.
const (
	UpdateEndpointJSONBodyUserVerificationDiscouraged UpdateEndpointJSONBodyUserVerification = "discouraged"
	UpdateEndpointJSONBodyUserVerificationPreferred   UpdateEndpointJSONBodyUserVerification = "preferred"
	UpdateEndpointJSONBodyUserVerificationRequired    UpdateEndpointJSONBodyUserVerification = "required"
)

// Valid indicates whether the value is a known member of the UpdateEndpointJSONBodyUserVerification enum.
func (e UpdateEndpointJSONBodyUserVerification) Valid() bool {
	switch e {
	case UpdateEndpointJSONBodyUserVerificationDiscouraged:
		return true
	case UpdateEndpointJSONBodyUserVerificationPreferred:
		return true
	case UpdateEndpointJSONBodyUserVerificationRequired:
		return true
	default:
		return false
	}
}

// Defines values for RegisterOauthClient201JSONResponseBodyTokenEndpointAuthMethod.
const (
	None RegisterOauthClient201JSONResponseBodyTokenEndpointAuthMethod = "none"
)

// Valid indicates whether the value is a known member of the RegisterOauthClient201JSONResponseBodyTokenEndpointAuthMethod enum.
func (e RegisterOauthClient201JSONResponseBodyTokenEndpointAuthMethod) Valid() bool {
	switch e {
	case None:
		return true
	default:
		return false
	}
}

// Defines values for RegisterOauthClient502JSONResponseBodyError.
const (
	ServerError RegisterOauthClient502JSONResponseBodyError = "server_error"
)

// Valid indicates whether the value is a known member of the RegisterOauthClient502JSONResponseBodyError enum.
func (e RegisterOauthClient502JSONResponseBodyError) Valid() bool {
	switch e {
	case ServerError:
		return true
	default:
		return false
	}
}

// Defines values for FinishInvitePasskeyRegistration200JSONResponseBodyStatus.
const (
	Registered FinishInvitePasskeyRegistration200JSONResponseBodyStatus = "registered"
)

// Valid indicates whether the value is a known member of the FinishInvitePasskeyRegistration200JSONResponseBodyStatus enum.
func (e FinishInvitePasskeyRegistration200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Registered:
		return true
	default:
		return false
	}
}

// Defines values for DeletePushSubscription200JSONResponseBodyOk.
const (
	DeletePushSubscription200JSONResponseBodyOkTrue DeletePushSubscription200JSONResponseBodyOk = true
)

// Valid indicates whether the value is a known member of the DeletePushSubscription200JSONResponseBodyOk enum.
func (e DeletePushSubscription200JSONResponseBodyOk) Valid() bool {
	switch e {
	case DeletePushSubscription200JSONResponseBodyOkTrue:
		return true
	default:
		return false
	}
}

// Defines values for CloseSession200JSONResponseBodyStatus.
const (
	Closed CloseSession200JSONResponseBodyStatus = "closed"
)

// Valid indicates whether the value is a known member of the CloseSession200JSONResponseBodyStatus enum.
func (e CloseSession200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Closed:
		return true
	default:
		return false
	}
}

// Defines values for ConfirmPasskey200JSONResponseBodyStatus.
const (
	Active ConfirmPasskey200JSONResponseBodyStatus = "active"
)

// Valid indicates whether the value is a known member of the ConfirmPasskey200JSONResponseBodyStatus enum.
func (e ConfirmPasskey200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Active:
		return true
	default:
		return false
	}
}

// Defines values for RevokePasskey200JSONResponseBodyStatus.
const (
	RevokePasskey200JSONResponseBodyStatusRevoked RevokePasskey200JSONResponseBodyStatus = "revoked"
)

// Valid indicates whether the value is a known member of the RevokePasskey200JSONResponseBodyStatus enum.
func (e RevokePasskey200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case RevokePasskey200JSONResponseBodyStatusRevoked:
		return true
	default:
		return false
	}
}

// Defines values for FinishPasskeyRegistration200JSONResponseBodyVerified.
const (
	True FinishPasskeyRegistration200JSONResponseBodyVerified = true
)

// Valid indicates whether the value is a known member of the FinishPasskeyRegistration200JSONResponseBodyVerified enum.
func (e FinishPasskeyRegistration200JSONResponseBodyVerified) Valid() bool {
	switch e {
	case True:
		return true
	default:
		return false
	}
}

// Defines values for StartStepUpJSONBodyAction.
const (
	StartStepUpJSONBodyActionConfirmPasskey    StartStepUpJSONBodyAction = "confirm_passkey"
	StartStepUpJSONBodyActionRegisterPasskey   StartStepUpJSONBodyAction = "register_passkey"
	StartStepUpJSONBodyActionRevokeAllSessions StartStepUpJSONBodyAction = "revoke_all_sessions"
	StartStepUpJSONBodyActionRevokePasskey     StartStepUpJSONBodyAction = "revoke_passkey"
	StartStepUpJSONBodyActionRevokeSession     StartStepUpJSONBodyAction = "revoke_session"
)

// Valid indicates whether the value is a known member of the StartStepUpJSONBodyAction enum.
func (e StartStepUpJSONBodyAction) Valid() bool {
	switch e {
	case StartStepUpJSONBodyActionConfirmPasskey:
		return true
	case StartStepUpJSONBodyActionRegisterPasskey:
		return true
	case StartStepUpJSONBodyActionRevokeAllSessions:
		return true
	case StartStepUpJSONBodyActionRevokePasskey:
		return true
	case StartStepUpJSONBodyActionRevokeSession:
		return true
	default:
		return false
	}
}

// Defines values for FinishStepUpJSONBodyAction.
const (
	FinishStepUpJSONBodyActionConfirmPasskey    FinishStepUpJSONBodyAction = "confirm_passkey"
	FinishStepUpJSONBodyActionRegisterPasskey   FinishStepUpJSONBodyAction = "register_passkey"
	FinishStepUpJSONBodyActionRevokeAllSessions FinishStepUpJSONBodyAction = "revoke_all_sessions"
	FinishStepUpJSONBodyActionRevokePasskey     FinishStepUpJSONBodyAction = "revoke_passkey"
	FinishStepUpJSONBodyActionRevokeSession     FinishStepUpJSONBodyAction = "revoke_session"
)

// Valid indicates whether the value is a known member of the FinishStepUpJSONBodyAction enum.
func (e FinishStepUpJSONBodyAction) Valid() bool {
	switch e {
	case FinishStepUpJSONBodyActionConfirmPasskey:
		return true
	case FinishStepUpJSONBodyActionRegisterPasskey:
		return true
	case FinishStepUpJSONBodyActionRevokeAllSessions:
		return true
	case FinishStepUpJSONBodyActionRevokePasskey:
		return true
	case FinishStepUpJSONBodyActionRevokeSession:
		return true
	default:
		return false
	}
}

// Defines values for GetHealth200JSONResponseBodyStatus.
const (
	Ok GetHealth200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyStatus enum.
func (e GetHealth200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// AuthSessionView defines model for AuthSessionView.
type AuthSessionView struct {
	AuthorizedAt *string `json:"authorizedAt"`
	ClientId     string  `json:"clientId"`
	ClientName   string  `json:"clientName"`
	CreatedAt    *string `json:"createdAt"`

	// Current True for the first-party web-UI client.
	Current bool     `json:"current"`
	Scopes  []string `json:"scopes"`
}

// AuthorizationServerMetadata RFC 8414 authorization-server metadata, blended: issuer + auth/token/jwks/ revocation point at Hydra; registration_endpoint points at ShellWatch's mediated DCR (/api/hydra/register).
type AuthorizationServerMetadata struct {
	AuthorizationEndpoint             string    `json:"authorization_endpoint"`
	CodeChallengeMethodsSupported     *[]string `json:"code_challenge_methods_supported,omitempty"`
	GrantTypesSupported               *[]string `json:"grant_types_supported,omitempty"`
	Issuer                            string    `json:"issuer"`
	JwksUri                           *string   `json:"jwks_uri,omitempty"`
	RegistrationEndpoint              string    `json:"registration_endpoint"`
	ResponseTypesSupported            *[]string `json:"response_types_supported,omitempty"`
	RevocationEndpoint                *string   `json:"revocation_endpoint,omitempty"`
	ScopesSupported                   *[]string `json:"scopes_supported,omitempty"`
	TokenEndpoint                     string    `json:"token_endpoint"`
	TokenEndpointAuthMethodsSupported *[]string `json:"token_endpoint_auth_methods_supported,omitempty"`
}

// Endpoint Endpoint as listed by GET /api/endpoints.
type Endpoint struct {
	AgentForward     bool                     `json:"agentForward"`
	Description      *string                  `json:"description"`
	Host             string                   `json:"host"`
	Id               string                   `json:"id"`
	IsDemo           bool                     `json:"isDemo"`
	Label            string                   `json:"label"`
	Port             int                      `json:"port"`
	UserVerification EndpointUserVerification `json:"userVerification"`
	Username         string                   `json:"username"`
}

// EndpointUserVerification defines model for Endpoint.UserVerification.
type EndpointUserVerification string

// Error Standard error envelope. Almost every 4xx/5xx returns this.
type Error struct {
	Error                string                 `json:"error"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// PendingActionView Client-safe projection of a pending signing action (resolve/reject omitted). Discriminated on `type`.
type PendingActionView struct {
	AccountId    string  `json:"accountId"`
	Challenge    *string `json:"challenge,omitempty"`
	ConnectionId *string `json:"connectionId,omitempty"`

	// Context SignRequestContext (source-tagged union)
	Context map[string]interface{} `json:"context"`

	// CreatedAt epoch ms
	CreatedAt    int     `json:"createdAt"`
	CredentialId *string `json:"credentialId,omitempty"`

	// ExpiresAt epoch ms
	ExpiresAt        int                                `json:"expiresAt"`
	Id               string                             `json:"id"`
	KeyFingerprint   *string                            `json:"keyFingerprint,omitempty"`
	KeyLabel         *string                            `json:"keyLabel,omitempty"`
	PasskeyLabel     *string                            `json:"passkeyLabel,omitempty"`
	RedirectTo       *string                            `json:"redirectTo,omitempty"`
	RpId             *string                            `json:"rpId,omitempty"`
	Status           PendingActionViewStatus            `json:"status"`
	Type             PendingActionViewType              `json:"type"`
	UserVerification *PendingActionViewUserVerification `json:"userVerification,omitempty"`
}

// PendingActionViewStatus defines model for PendingActionView.Status.
type PendingActionViewStatus string

// PendingActionViewType defines model for PendingActionView.Type.
type PendingActionViewType string

// PendingActionViewUserVerification defines model for PendingActionView.UserVerification.
type PendingActionViewUserVerification string

// ProtectedResourceMetadata RFC 9728 protected-resource metadata. Emitted by `resourceMetadata(scope)` in src/hydra/routes.ts for the `/mcp` and `/agent-proxy` resources.
type ProtectedResourceMetadata struct {
	// AuthorizationServers Points back at this deployment's AS metadata origin (externalUrl).
	AuthorizationServers   []string `json:"authorization_servers"`
	BearerMethodsSupported []string `json:"bearer_methods_supported"`

	// Resource Absolute URL of the guarded resource (externalUrl + /mcp or /agent-proxy).
	Resource string `json:"resource"`

	// ScopesSupported The resource scope (mcp|agent) plus offline_access.
	ScopesSupported []string `json:"scopes_supported"`
}

// SessionLifecyclePage defines model for SessionLifecyclePage.
type SessionLifecyclePage struct {
	// NextCursor Opaque cursor; null on the final page.
	NextCursor *string               `json:"nextCursor"`
	Rows       []SessionLifecycleRow `json:"rows"`
}

// SessionLifecycleRow defines model for SessionLifecycleRow.
type SessionLifecycleRow struct {
	AccountId        *string                    `json:"accountId,omitempty"`
	ClientHostname   *string                    `json:"clientHostname,omitempty"`
	ClientOs         *string                    `json:"clientOs,omitempty"`
	ClientVersion    *string                    `json:"clientVersion,omitempty"`
	CloseReason      *string                    `json:"closeReason,omitempty"`
	ClosedAt         *string                    `json:"closedAt,omitempty"`
	CreatedAt        *string                    `json:"createdAt,omitempty"`
	DurationMs       *int                       `json:"durationMs,omitempty"`
	EndpointId       *string                    `json:"endpointId,omitempty"`
	McpClientName    *string                    `json:"mcpClientName,omitempty"`
	McpClientVersion *string                    `json:"mcpClientVersion,omitempty"`
	McpReason        *string                    `json:"mcpReason,omitempty"`
	SessionId        *string                    `json:"sessionId,omitempty"`
	Source           *SessionLifecycleRowSource `json:"source,omitempty"`
	SourceIp         *string                    `json:"sourceIp,omitempty"`
	Status           *SessionLifecycleRowStatus `json:"status,omitempty"`
}

// SessionLifecycleRowSource defines model for SessionLifecycleRow.Source.
type SessionLifecycleRowSource string

// SessionLifecycleRowStatus defines model for SessionLifecycleRow.Status.
type SessionLifecycleRowStatus string

// SigningRequestPage defines model for SigningRequestPage.
type SigningRequestPage struct {
	NextCursor *string             `json:"nextCursor"`
	Rows       []SigningRequestRow `json:"rows"`
}

// SigningRequestRow defines model for SigningRequestRow.
type SigningRequestRow struct {
	AccountId        *string                   `json:"accountId,omitempty"`
	CancelReason     *string                   `json:"cancelReason,omitempty"`
	ClientHostname   *string                   `json:"clientHostname,omitempty"`
	ClientOs         *string                   `json:"clientOs,omitempty"`
	ClientVersion    *string                   `json:"clientVersion,omitempty"`
	CreatedAt        *string                   `json:"createdAt,omitempty"`
	CredentialId     *string                   `json:"credentialId,omitempty"`
	EndpointAddress  *string                   `json:"endpointAddress,omitempty"`
	EndpointLabel    *string                   `json:"endpointLabel,omitempty"`
	Id               *string                   `json:"id,omitempty"`
	KeyFingerprint   *string                   `json:"keyFingerprint,omitempty"`
	KeyLabel         *string                   `json:"keyLabel,omitempty"`
	LatencyMs        *int                      `json:"latencyMs,omitempty"`
	McpClientName    *string                   `json:"mcpClientName,omitempty"`
	McpClientVersion *string                   `json:"mcpClientVersion,omitempty"`
	McpReason        *string                   `json:"mcpReason,omitempty"`
	Outcome          *SigningRequestRowOutcome `json:"outcome,omitempty"`
	PasskeyLabel     *string                   `json:"passkeyLabel,omitempty"`
	ResolvedAt       *string                   `json:"resolvedAt,omitempty"`
	SessionId        *string                   `json:"sessionId,omitempty"`
	Source           *SigningRequestRowSource  `json:"source,omitempty"`
	SourceIp         *string                   `json:"sourceIp,omitempty"`
	Type             *string                   `json:"type,omitempty"`
	UserVerification *string                   `json:"userVerification,omitempty"`
}

// SigningRequestRowOutcome defines model for SigningRequestRow.Outcome.
type SigningRequestRowOutcome string

// SigningRequestRowSource defines model for SigningRequestRow.Source.
type SigningRequestRowSource string

// StatusCreated defines model for StatusCreated.
type StatusCreated struct {
	Id     string              `json:"id"`
	Status StatusCreatedStatus `json:"status"`
}

// StatusCreatedStatus defines model for StatusCreated.Status.
type StatusCreatedStatus string

// StatusDeleted defines model for StatusDeleted.
type StatusDeleted struct {
	Status StatusDeletedStatus `json:"status"`
}

// StatusDeletedStatus defines model for StatusDeleted.Status.
type StatusDeletedStatus string

// StatusUpdated defines model for StatusUpdated.
type StatusUpdated struct {
	Status StatusUpdatedStatus `json:"status"`
}

// StatusUpdatedStatus defines model for StatusUpdated.Status.
type StatusUpdatedStatus string

// StepUpError Error body returned by the step-up gate (401).
type StepUpError struct {
	Code  StepUpErrorCode `json:"code"`
	Error string          `json:"error"`
}

// StepUpErrorCode defines model for StepUpError.Code.
type StepUpErrorCode string

// TerminalSession Returned verbatim by POST /api/sessions and inside GET /api/sessions. Mirrors src/terminal/types.ts TerminalSession (Date fields serialize to ISO-8601 strings over the wire).
type TerminalSession struct {
	AccountId        string         `json:"accountId"`
	CloseReason      *string        `json:"closeReason,omitempty"`
	CreatedAt        string         `json:"createdAt"`
	EndpointId       string         `json:"endpointId"`
	LastActivityAt   string         `json:"lastActivityAt"`
	McpClientName    *string        `json:"mcpClientName,omitempty"`
	McpClientVersion *string        `json:"mcpClientVersion,omitempty"`
	McpReason        *string        `json:"mcpReason,omitempty"`
	SessionId        string         `json:"sessionId"`
	Source           TerminalSource `json:"source"`
	SourceIp         *string        `json:"sourceIp,omitempty"`
	Status           TerminalStatus `json:"status"`
}

// TerminalSource defines model for TerminalSource.
type TerminalSource string

// TerminalStatus defines model for TerminalStatus.
type TerminalStatus string

// WebAuthnAuthenticationOptions @simplewebauthn generateAuthenticationOptions() output, spread at the top level alongside `challengeId` (and `action` for step-up). Modeled loosely.
type WebAuthnAuthenticationOptions struct {
	ChallengeId          *string                `json:"challengeId,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// WebAuthnRegistrationOptions @simplewebauthn generateRegistrationOptions() output, spread at the top level alongside `challengeId`. Modeled loosely.
type WebAuthnRegistrationOptions struct {
	ChallengeId          *string                `json:"challengeId,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// StepUpTokenHeader defines model for StepUpTokenHeader.
type StepUpTokenHeader = string

// Forbidden Standard error envelope. Almost every 4xx/5xx returns this.
type Forbidden = Error

// NotFound Standard error envelope. Almost every 4xx/5xx returns this.
type NotFound = Error

// StepUpRequired Error body returned by the step-up gate (401).
type StepUpRequired = StepUpError

// Unauthorized Standard error envelope. Almost every 4xx/5xx returns this.
type Unauthorized = Error

// bearerAgentContextKey is the context key for bearerAgent security scheme
type bearerAgentContextKey string

// bearerMcpContextKey is the context key for bearerMcp security scheme
type bearerMcpContextKey string

// bearerUiContextKey is the context key for bearerUi security scheme
type bearerUiContextKey string

// DenyAction200JSONResponseBodyStatus defines parameters for DenyAction.
type DenyAction200JSONResponseBodyStatus string

// ResolveActionJSONBody defines parameters for ResolveAction.
type ResolveActionJSONBody struct {
	// AuthenticatorData base64url
	AuthenticatorData *string `json:"authenticatorData,omitempty"`

	// ClientDataJSON base64url
	ClientDataJSON *string `json:"clientDataJSON,omitempty"`

	// Signature base64url
	Signature *string `json:"signature,omitempty"`
}

// ListAuditSessionsParams defines parameters for ListAuditSessions.
type ListAuditSessionsParams struct {
	EndpointId *string `form:"endpointId,omitempty" json:"endpointId,omitempty"`
	From       *string `form:"from,omitempty" json:"from,omitempty"`
	To         *string `form:"to,omitempty" json:"to,omitempty"`
	Cursor     *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Clamped server-side (clampLimit): non-finite or ≤0 → 50; values above 500 → 500. Default 50, max 500.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAuditSigningsParams defines parameters for ListAuditSignings.
type ListAuditSigningsParams struct {
	Source  *ListAuditSigningsParamsSource  `form:"source,omitempty" json:"source,omitempty"`
	Outcome *ListAuditSigningsParamsOutcome `form:"outcome,omitempty" json:"outcome,omitempty"`
	From    *string                         `form:"from,omitempty" json:"from,omitempty"`
	To      *string                         `form:"to,omitempty" json:"to,omitempty"`
	Cursor  *string                         `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Page size. Clamped server-side (clampLimit): non-finite or ≤0 → 50; values above 500 → 500. Default 50, max 500.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAuditSigningsParamsSource defines parameters for ListAuditSignings.
type ListAuditSigningsParamsSource string

// ListAuditSigningsParamsOutcome defines parameters for ListAuditSignings.
type ListAuditSigningsParamsOutcome string

// UpdateCurrentAccountJSONBody defines parameters for UpdateCurrentAccount.
type UpdateCurrentAccountJSONBody struct {
	Name              *string `json:"name,omitempty"`
	ShowDemoEndpoints *bool   `json:"showDemoEndpoints,omitempty"`
}

// FinishAccountRegistrationJSONBody defines parameters for FinishAccountRegistration.
type FinishAccountRegistrationJSONBody struct {
	ChallengeId string      `json:"challengeId"`
	Credential  interface{} `json:"credential"`
	Name        string      `json:"name"`
}

// FinishAccountRegistration200JSONResponseBodyVerified defines parameters for FinishAccountRegistration.
type FinishAccountRegistration200JSONResponseBodyVerified bool

// StartAccountRegistrationJSONBody defines parameters for StartAccountRegistration.
type StartAccountRegistrationJSONBody struct {
	Name *string `json:"name,omitempty"`
}

// RevokeAllAuthorizedClientsParams defines parameters for RevokeAllAuthorizedClients.
type RevokeAllAuthorizedClientsParams struct {
	// XShellWatchStepUpToken Single-use step-up token minted by POST /api/webauthn/stepup/verify, bound to the specific action. Sent on the header `x-shellwatch-stepup-token`. Absent/expired/wrong-action/wrong-account → 401.
	XShellWatchStepUpToken StepUpTokenHeader `json:"X-ShellWatch-StepUp-Token"`
}

// RevokeAllAuthorizedClients200JSONResponseBodyStatus defines parameters for RevokeAllAuthorizedClients.
type RevokeAllAuthorizedClients200JSONResponseBodyStatus string

// RevokeAuthorizedClientParams defines parameters for RevokeAuthorizedClient.
type RevokeAuthorizedClientParams struct {
	// XShellWatchStepUpToken Single-use step-up token minted by POST /api/webauthn/stepup/verify, bound to the specific action. Sent on the header `x-shellwatch-stepup-token`. Absent/expired/wrong-action/wrong-account → 401.
	XShellWatchStepUpToken StepUpTokenHeader `json:"X-ShellWatch-StepUp-Token"`
}

// RevokeAuthorizedClient200JSONResponseBodyStatus defines parameters for RevokeAuthorizedClient.
type RevokeAuthorizedClient200JSONResponseBodyStatus string

// CreateEndpointJSONBody defines parameters for CreateEndpoint.
type CreateEndpointJSONBody struct {
	AgentForward     *bool                                   `json:"agentForward,omitempty"`
	Description      *string                                 `json:"description,omitempty"`
	Host             string                                  `json:"host"`
	Label            string                                  `json:"label"`
	Port             *int                                    `json:"port,omitempty"`
	UserVerification *CreateEndpointJSONBodyUserVerification `json:"userVerification,omitempty"`
	Username         *string                                 `json:"username,omitempty"`
}

// CreateEndpointJSONBodyUserVerification defines parameters for CreateEndpoint.
type CreateEndpointJSONBodyUserVerification string

// UpdateEndpointJSONBody defines parameters for UpdateEndpoint.
type UpdateEndpointJSONBody struct {
	AgentForward     *bool                                   `json:"agentForward,omitempty"`
	Description      *string                                 `json:"description,omitempty"`
	Host             *string                                 `json:"host,omitempty"`
	Label            *string                                 `json:"label,omitempty"`
	Port             *int                                    `json:"port,omitempty"`
	UserVerification *UpdateEndpointJSONBodyUserVerification `json:"userVerification,omitempty"`
	Username         *string                                 `json:"username,omitempty"`
}

// UpdateEndpointJSONBodyUserVerification defines parameters for UpdateEndpoint.
type UpdateEndpointJSONBodyUserVerification string

// FinishHydraLoginJSONBody defines parameters for FinishHydraLogin.
type FinishHydraLoginJSONBody struct {
	ChallengeId    *string     `json:"challengeId,omitempty"`
	Credential     interface{} `json:"credential,omitempty"`
	LoginChallenge *string     `json:"login_challenge,omitempty"`
}

// RegisterOauthClientJSONBody defines parameters for RegisterOauthClient.
type RegisterOauthClientJSONBody struct {
	ClientName   *string  `json:"client_name,omitempty"`
	RedirectUris []string `json:"redirect_uris"`

	// Scope space-delimited; subset of allowed
	Scope *string `json:"scope,omitempty"`
}

// RegisterOauthClient201JSONResponseBodyTokenEndpointAuthMethod defines parameters for RegisterOauthClient.
type RegisterOauthClient201JSONResponseBodyTokenEndpointAuthMethod string

// RegisterOauthClient502JSONResponseBodyError defines parameters for RegisterOauthClient.
type RegisterOauthClient502JSONResponseBodyError string

// FinishInvitePasskeyRegistrationJSONBody defines parameters for FinishInvitePasskeyRegistration.
type FinishInvitePasskeyRegistrationJSONBody struct {
	ChallengeId string      `json:"challengeId"`
	Credential  interface{} `json:"credential"`
	Token       string      `json:"token"`
}

// FinishInvitePasskeyRegistration200JSONResponseBodyStatus defines parameters for FinishInvitePasskeyRegistration.
type FinishInvitePasskeyRegistration200JSONResponseBodyStatus string

// StartInvitePasskeyRegistrationJSONBody defines parameters for StartInvitePasskeyRegistration.
type StartInvitePasskeyRegistrationJSONBody struct {
	Token string `json:"token"`
}

// DeletePushSubscriptionJSONBody defines parameters for DeletePushSubscription.
type DeletePushSubscriptionJSONBody struct {
	Endpoint string `json:"endpoint"`
}

// DeletePushSubscription200JSONResponseBodyOk defines parameters for DeletePushSubscription.
type DeletePushSubscription200JSONResponseBodyOk bool

// CreatePushSubscriptionJSONBody defines parameters for CreatePushSubscription.
type CreatePushSubscriptionJSONBody struct {
	Endpoint string `json:"endpoint"`
	Keys     struct {
		Auth   string `json:"auth"`
		P256dh string `json:"p256dh"`
	} `json:"keys"`
}

// CreateSessionJSONBody defines parameters for CreateSession.
type CreateSessionJSONBody struct {
	EndpointId string `json:"endpointId"`
}

// CloseSession200JSONResponseBodyStatus defines parameters for CloseSession.
type CloseSession200JSONResponseBodyStatus string

// GetSessionTailParams defines parameters for GetSessionTail.
type GetSessionTailParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// ConfirmPasskeyParams defines parameters for ConfirmPasskey.
type ConfirmPasskeyParams struct {
	// XShellWatchStepUpToken Single-use step-up token minted by POST /api/webauthn/stepup/verify, bound to the specific action. Sent on the header `x-shellwatch-stepup-token`. Absent/expired/wrong-action/wrong-account → 401.
	XShellWatchStepUpToken StepUpTokenHeader `json:"X-ShellWatch-StepUp-Token"`
}

// ConfirmPasskey200JSONResponseBodyStatus defines parameters for ConfirmPasskey.
type ConfirmPasskey200JSONResponseBodyStatus string

// UpdatePasskeyLabelJSONBody defines parameters for UpdatePasskeyLabel.
type UpdatePasskeyLabelJSONBody struct {
	Label string `json:"label"`
}

// RevokePasskeyJSONBody defines parameters for RevokePasskey.
type RevokePasskeyJSONBody struct {
	InvalidateSessions *bool `json:"invalidateSessions,omitempty"`
}

// RevokePasskeyParams defines parameters for RevokePasskey.
type RevokePasskeyParams struct {
	// XShellWatchStepUpToken Single-use step-up token minted by POST /api/webauthn/stepup/verify, bound to the specific action. Sent on the header `x-shellwatch-stepup-token`. Absent/expired/wrong-action/wrong-account → 401.
	XShellWatchStepUpToken StepUpTokenHeader `json:"X-ShellWatch-StepUp-Token"`
}

// RevokePasskey200JSONResponseBodyStatus defines parameters for RevokePasskey.
type RevokePasskey200JSONResponseBodyStatus string

// FinishPasskeyRegistrationJSONBody defines parameters for FinishPasskeyRegistration.
type FinishPasskeyRegistrationJSONBody struct {
	ChallengeId string      `json:"challengeId"`
	Credential  interface{} `json:"credential"`
}

// FinishPasskeyRegistrationParams defines parameters for FinishPasskeyRegistration.
type FinishPasskeyRegistrationParams struct {
	// XShellWatchStepUpToken Single-use step-up token minted by POST /api/webauthn/stepup/verify, bound to the specific action. Sent on the header `x-shellwatch-stepup-token`. Absent/expired/wrong-action/wrong-account → 401.
	XShellWatchStepUpToken StepUpTokenHeader `json:"X-ShellWatch-StepUp-Token"`
}

// FinishPasskeyRegistration200JSONResponseBodyVerified defines parameters for FinishPasskeyRegistration.
type FinishPasskeyRegistration200JSONResponseBodyVerified bool

// StartPasskeyRegistrationJSONBody defines parameters for StartPasskeyRegistration.
type StartPasskeyRegistrationJSONBody struct {
	Label string  `json:"label"`
	Name  *string `json:"name,omitempty"`
}

// StartStepUpJSONBody defines parameters for StartStepUp.
type StartStepUpJSONBody struct {
	Action StartStepUpJSONBodyAction `json:"action"`
}

// StartStepUpJSONBodyAction defines parameters for StartStepUp.
type StartStepUpJSONBodyAction string

// FinishStepUpJSONBody defines parameters for FinishStepUp.
type FinishStepUpJSONBody struct {
	Action      FinishStepUpJSONBodyAction `json:"action"`
	ChallengeId string                     `json:"challengeId"`
	Credential  interface{}                `json:"credential"`
}

// FinishStepUpJSONBodyAction defines parameters for FinishStepUp.
type FinishStepUpJSONBodyAction string

// GetHealth200JSONResponseBodyStatus defines parameters for GetHealth.
type GetHealth200JSONResponseBodyStatus string

// ResolveActionJSONRequestBody defines body for ResolveAction for application/json ContentType.
type ResolveActionJSONRequestBody ResolveActionJSONBody

// UpdateCurrentAccountJSONRequestBody defines body for UpdateCurrentAccount for application/json ContentType.
type UpdateCurrentAccountJSONRequestBody UpdateCurrentAccountJSONBody

// FinishAccountRegistrationJSONRequestBody defines body for FinishAccountRegistration for application/json ContentType.
type FinishAccountRegistrationJSONRequestBody FinishAccountRegistrationJSONBody

// StartAccountRegistrationJSONRequestBody defines body for StartAccountRegistration for application/json ContentType.
type StartAccountRegistrationJSONRequestBody StartAccountRegistrationJSONBody

// CreateEndpointJSONRequestBody defines body for CreateEndpoint for application/json ContentType.
type CreateEndpointJSONRequestBody CreateEndpointJSONBody

// UpdateEndpointJSONRequestBody defines body for UpdateEndpoint for application/json ContentType.
type UpdateEndpointJSONRequestBody UpdateEndpointJSONBody

// FinishHydraLoginJSONRequestBody defines body for FinishHydraLogin for application/json ContentType.
type FinishHydraLoginJSONRequestBody FinishHydraLoginJSONBody

// RegisterOauthClientJSONRequestBody defines body for RegisterOauthClient for application/json ContentType.
type RegisterOauthClientJSONRequestBody RegisterOauthClientJSONBody

// FinishInvitePasskeyRegistrationJSONRequestBody defines body for FinishInvitePasskeyRegistration for application/json ContentType.
type FinishInvitePasskeyRegistrationJSONRequestBody FinishInvitePasskeyRegistrationJSONBody

// StartInvitePasskeyRegistrationJSONRequestBody defines body for StartInvitePasskeyRegistration for application/json ContentType.
type StartInvitePasskeyRegistrationJSONRequestBody StartInvitePasskeyRegistrationJSONBody

// DeletePushSubscriptionJSONRequestBody defines body for DeletePushSubscription for application/json ContentType.
type DeletePushSubscriptionJSONRequestBody DeletePushSubscriptionJSONBody

// CreatePushSubscriptionJSONRequestBody defines body for CreatePushSubscription for application/json ContentType.
type CreatePushSubscriptionJSONRequestBody CreatePushSubscriptionJSONBody

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody CreateSessionJSONBody

// UpdatePasskeyLabelJSONRequestBody defines body for UpdatePasskeyLabel for application/json ContentType.
type UpdatePasskeyLabelJSONRequestBody UpdatePasskeyLabelJSONBody

// RevokePasskeyJSONRequestBody defines body for RevokePasskey for application/json ContentType.
type RevokePasskeyJSONRequestBody RevokePasskeyJSONBody

// FinishPasskeyRegistrationJSONRequestBody defines body for FinishPasskeyRegistration for application/json ContentType.
type FinishPasskeyRegistrationJSONRequestBody FinishPasskeyRegistrationJSONBody

// StartPasskeyRegistrationJSONRequestBody defines body for StartPasskeyRegistration for application/json ContentType.
type StartPasskeyRegistrationJSONRequestBody StartPasskeyRegistrationJSONBody

// StartStepUpJSONRequestBody defines body for StartStepUp for application/json ContentType.
type StartStepUpJSONRequestBody StartStepUpJSONBody

// FinishStepUpJSONRequestBody defines body for FinishStepUp for application/json ContentType.
type FinishStepUpJSONRequestBody FinishStepUpJSONBody

// Getter for additional properties for Error. Returns the specified
// element and whether it was found
func (a Error) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Error
func (a *Error) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Error to handle AdditionalProperties
func (a *Error) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Error to handle AdditionalProperties
func (a Error) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WebAuthnAuthenticationOptions. Returns the specified
// element and whether it was found
func (a WebAuthnAuthenticationOptions) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WebAuthnAuthenticationOptions
func (a *WebAuthnAuthenticationOptions) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WebAuthnAuthenticationOptions to handle AdditionalProperties
func (a *WebAuthnAuthenticationOptions) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challengeId"]; found {
		err = json.Unmarshal(raw, &a.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challengeId': %w", err)
		}
		delete(object, "challengeId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WebAuthnAuthenticationOptions to handle AdditionalProperties
func (a WebAuthnAuthenticationOptions) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ChallengeId != nil {
		object["challengeId"], err = json.Marshal(a.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challengeId': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for WebAuthnRegistrationOptions. Returns the specified
// element and whether it was found
func (a WebAuthnRegistrationOptions) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for WebAuthnRegistrationOptions
func (a *WebAuthnRegistrationOptions) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for WebAuthnRegistrationOptions to handle AdditionalProperties
func (a *WebAuthnRegistrationOptions) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["challengeId"]; found {
		err = json.Unmarshal(raw, &a.ChallengeId)
		if err != nil {
			return fmt.Errorf("error reading 'challengeId': %w", err)
		}
		delete(object, "challengeId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for WebAuthnRegistrationOptions to handle AdditionalProperties
func (a WebAuthnRegistrationOptions) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ChallengeId != nil {
		object["challengeId"], err = json.Marshal(a.ChallengeId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'challengeId': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
